Lazy load metrics listener
DataDog/datadog-lambda-js pull request #320
Opened 2022-11-09 20:59 UTC by amymin00

### What does this PR do?

Remove loading of metrics listener whenever using the extension. Instead, lazy import metrics listener only when user intends to send a distribution metric. Decreases loading of the extension by 57ms.

### Motivation

Reducing layer sizes during serverless week

### Testing Guidelines

Ran existing unit tests and integration tests. Ensured metrics are still sent when sendDistributionMetric is called.

### Additional Notes

### Types of Changes

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [x] Misc (docs, refactoring, dependency upgrade, etc.)

### Check all that apply

- [ ] This PR's description is comprehensive
- [ ] This PR contains breaking changes that are documented in the description
- [ ] This PR introduces new APIs or parameters that are documented and unlikely to change in the foreseeable future
- [ ] This PR impacts documentation, and it has been updated (or a ticket has been logged)
- [ ] This PR's changes are covered by the automated tests
- [ ] This PR collects user input/sensitive content into Datadog
- [x] This PR passes the integration tests (ask a Datadog member to run the tests)

2022-11-10 19:44 UTC, astuyve requested changes

2022-11-10 19:44 UTC, astuyve commented on src/index.ts
> +const EXTENSION_PATH = "/opt/extensions/datadog-agent";
We declare this constant twice, think we can export this function into a utility method so we can use it in one place?
https://github.com/DataDog/datadog-lambda-js/blob/54a6a1436c498009060d6966df8349ea929adc22/src/metrics/extension.ts#L8-L16

2022-11-11 18:15 UTC, astuyve commented on src/index.ts
> +  if (!isExtensionEnabled()) {
I think we need a test covering this in index.spec.ts as well

2022-12-06 21:24 UTC, astuyve approved these changes
LGTM! We can release once we test against our self monitoring apps and confirm the behavior, but the integration tests passing here are already a strong indicator. Nice work!

2022-12-12 16:53 UTC, joeyzhao2018 approved these changes

2022-12-13 19:35 UTC, merged